### ISSUE TITLE
Script does not work on a clean profile of firefox

### ISSUE THREAD

**Issue by marius851000** [r-ainbowroad/2023-minimap#11]
So... I tried to install it. Failed (maybe another installed extension), so I open a clean profile of firefox (``firefox --profile <path>``), but it still does not work.

I have some issues that say:

```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://6b91e9f3-2173-4bc0-9b98-9f1c5b0320ff/%20r%EF%BC%8Fplace%20MLP%20Minimap.user.js#1
Source Map URL: minimap.user.js.map
```

I’ll try to fix this.

**Comment by marius851000** [comment]
The whole related error being:
```
[2023-07-20T16:06:31.000Z] Found canvas:  
<canvas>
r／place MLP Minimap.user.js:29:7708
Known site detected. Attempting to load site specific handler.[ r／place MLP Minimap.user.js:29:8323](moz-extension://6b91e9f3-2173-4bc0-9b98-9f1c5b0320ff/%20r%EF%BC%8Fplace%20MLP%20Minimap.user.js#1)
Failed to find `mona-lisa-embed`[ r／place MLP Minimap.user.js:29:8539](moz-extension://6b91e9f3-2173-4bc0-9b98-9f1c5b0320ff/%20r%EF%BC%8Fplace%20MLP%20Minimap.user.js#1)
Retries left: 3[ r／place MLP Minimap.user.js:29:8863](moz-extension://6b91e9f3-2173-4bc0-9b98-9f1c5b0320ff/%20r%EF%BC%8Fplace%20MLP%20Minimap.user.js#1)
Firefox can’t establish a connection to the server at wss://gql-realtime-2.reddit.com/query. [client.js:446:22](https://garlic-bread.reddit.com/node_modules/subscriptions-transport-ws/dist/client.js)
The connection to wss://gql-realtime-2.reddit.com/query was interrupted while the page was loading. [client.js:446:22](https://garlic-bread.reddit.com/node_modules/subscriptions-transport-ws/dist/client.js)
Failed to find `mona-lisa-embed`[ r／place MLP Minimap.user.js:29:8539](moz-extension://6b91e9f3-2173-4bc0-9b98-9f1c5b0320ff/%20r%EF%BC%8Fplace%20MLP%20Minimap.user.js#1)
Retries left: 2[ r／place MLP Minimap.user.js:29:8863](moz-extension://6b91e9f3-2173-4bc0-9b98-9f1c5b0320ff/%20r%EF%BC%8Fplace%20MLP%20Minimap.user.js#1)
Firefox can’t establish a connection to the server at wss://gql-realtime-2.reddit.com/query. [client.js:446:22](https://garlic-bread.reddit.com/node_modules/subscriptions-transport-ws/dist/client.js)
The connection to wss://gql-realtime-2.reddit.com/query was interrupted while the page was loading. [client.js:446:22](https://garlic-bread.reddit.com/node_modules/subscriptions-transport-ws/dist/client.js)
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://6b91e9f3-2173-4bc0-9b98-9f1c5b0320ff/%20r%EF%BC%8Fplace%20MLP%20Minimap.user.js#1
Source Map URL: minimap.user.js.map

Failed to find `mona-lisa-embed`[ r／place MLP Minimap.user.js:29:8539](moz-extension://6b91e9f3-2173-4bc0-9b98-9f1c5b0320ff/%20r%EF%BC%8Fplace%20MLP%20Minimap.user.js#1)
Retries left: 1[ r／place MLP Minimap.user.js:29:8863](moz-extension://6b91e9f3-2173-4bc0-9b98-9f1c5b0320ff/%20r%EF%BC%8Fplace%20MLP%20Minimap.user.js#1)
[2023-07-20T16:06:34.186Z] Failed to find site specific handler. Falling back to overlay.
```

**Comment by marius851000** [comment]
It happen that directly loading the minimap.user.js solve the problem.

(and so, the issue is with ``loader.user.js``)

**Comment by marius851000** [comment]
*If someone could told me how to use the .map with violentmonkey. Or another one of the like.*

**Comment by marius851000** [comment]
In the end, firefox complains CSP. Likely this issues. https://github.com/r-ainbowroad/2023-minimap/issues/10

**Comment by marius851000** [comment]
Indeed, putting ``@inject-into content`` make it work.

**Comment by marius851000** [comment]
Doesn’t work with GreaseMonkey + Firefox, but also didn’t work previously

**Comment by marius851000** [comment]
Greasemonkey not on chrome, problem solved.

**Comment by marius851000** [comment]
Violentmonkey on chromium work. Will finally do a PR.

**Comment by Ponywka** [comment]
ViolentMonkey on Chromium doesn't work. It causes problems in the work of the minimap.
